language: ruby
rvm:
- 2.2.0

services:
  - mongodb
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

deploy:
  provider: heroku
  api_key:
    secure: bhfGFajpFcdjNjwxAa7PunpkRgIAKCLM40rFByqSxr3NBiIOhICtyI6rAJG60SXCSLz7S+HYR+f4MyciLy2JEBg/b8CFHV4zHtHQ9LMJRlS0jsOEgGYdYHx6WkqIteK9Vu+mFaAEGb+eWeRfGeXvgcrCa5Xf+xJJieJtlLNWMgM=
  app: come-malaka-expenses
  on:
    repo: Elyasin/Come-Malaka-Expenses

before_script:
  - sleep 15
  - psql -c "create role tester with createdb login password 'tester'" -U postgres
  - rake db:setup
