language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.c"
  - "2.1.x"
  - "2.2.x"
#User MongoDB for tests
services: mongodb
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec specdf