language: ruby
rvm:
- 2.2.0
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: bhfGFajpFcdjNjwxAa7PunpkRgIAKCLM40rFByqSxr3NBiIOhICtyI6rAJG60SXCSLz7S+HYR+f4MyciLy2JEBg/b8CFHV4zHtHQ9LMJRlS0jsOEgGYdYHx6WkqIteK9Vu+mFaAEGb+eWeRfGeXvgcrCa5Xf+xJJieJtlLNWMgM=
  app: come-malaka-expenses
  on:
    repo: Elyasin/Come-Malaka-Expenses
