language: ruby
rvm:
- 2.2.0

addons:
  postgresql: "9.4"

deploy:
  provider: heroku
  api_key:
    secure: bhfGFajpFcdjNjwxAa7PunpkRgIAKCLM40rFByqSxr3NBiIOhICtyI6rAJG60SXCSLz7S+HYR+f4MyciLy2JEBg/b8CFHV4zHtHQ9LMJRlS0jsOEgGYdYHx6WkqIteK9Vu+mFaAEGb+eWeRfGeXvgcrCa5Xf+xJJieJtlLNWMgM=
  app: come-malaka-expenses
  on:
    repo: Elyasin/Come-Malaka-Expenses

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.0.7 mongodb-org-server=3.0.7 mongodb-org-shell=3.0.7 mongodb-org-mongos=3.0.7 mongodb-org-tools=3.0.7
  - sudo service mongod start
  - sleep 15
  - mongo come_malaka_test --eval "db.createUser({user:'tester',pwd:'tester',roles:['readWrite']});"
  - psql -c "create role tester with createdb login password 'tester'" -U postgres
  - bundle exec rake db:setup
